# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agradable', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True, max_length=300)),
                ('personaje1', models.CharField(blank=True, max_length=40)),
                ('personaje2', models.CharField(blank=True, max_length=40)),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_pregunta', models.CharField(max_length=30)),
                ('sad_image', models.CharField(max_length=30)),
                ('happy_image', models.CharField(max_length=30)),
                ('btn_continuar', models.CharField(max_length=30)),
                ('btn_cancelar', models.CharField(max_length=30)),
                ('btn_confirmar', models.CharField(max_length=30)),
                ('sad_mensaje', models.TextField(max_length=200)),
                ('happy_mensaje', models.TextField(max_length=200)),
                ('ayuda1', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MenuIdioma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(max_length=30)),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='idioma',
            name='lenguaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idioma_traductor', to='dreams.MenuIdioma'),
        ),
    ]
