# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dream',
            name='nombre_sueño',
            field=models.CharField(default='prueba', max_length=30),
            preserve_default=False,
        ),
    ]
