# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0002_auto_20180202_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='nombre_sueño',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
