# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0003_auto_20180202_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='idioma',
            name='agregar',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='idioma',
            name='ejemplo',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='idioma',
            name='parrafo1',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='idioma',
            name='parrafo2',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='idioma',
            name='parrafo3',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='idioma',
            name='parrafo4',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='idioma',
            name='parrafo5',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='idioma',
            name='parrafo6',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='idioma',
            name='parrafo7',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='idioma',
            name='parrafo8',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='idioma',
            name='placeholder',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='idioma',
            name='sub_pregunta2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='idioma',
            name='sub_pregunta3',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
