# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-09 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0004_auto_20180202_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dream',
            old_name='nombre_sueño',
            new_name='nombre_sueno',
        ),
        migrations.AddField(
            model_name='idioma',
            name='buho1',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='idioma',
            name='buho2',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='idioma',
            name='buho3',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='idioma',
            name='buho4',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='idioma',
            name='buho5',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='idioma',
            name='buho6',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='idioma',
            name='instruccion_p1',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='idioma',
            name='instruccion_p2',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='agregar',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='ejemplo',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='happy_image',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='parrafo1',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='parrafo2',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='parrafo3',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='parrafo4',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='parrafo5',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='parrafo6',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='parrafo7',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='parrafo8',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='placeholder',
            field=models.TextField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='sad_image',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='sub_pregunta',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='sub_pregunta2',
            field=models.TextField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='sub_pregunta3',
            field=models.TextField(blank=True, max_length=800),
        ),
    ]
