# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-09 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0005_auto_20180309_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='idioma',
            name='btn_personaje1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='idioma',
            name='btn_personaje5',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='idioma',
            name='opcion1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='idioma',
            name='opcion2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='idioma',
            name='opcion3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='idioma',
            name='opcion4',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='idioma',
            name='placeholder_chat',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
