# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-14 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0006_auto_20180309_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='idioma',
            name='ayuda2',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='idioma',
            name='ayuda3',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='idioma',
            name='ayuda4',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='idioma',
            name='ayuda5',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='idioma',
            name='ayuda6',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='idioma',
            name='ayuda7',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='idioma',
            name='ayuda8',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='idioma',
            name='pregunta_personaje',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
