# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-28 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0007_auto_20180314_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(max_length=2000)),
                ('buho', models.CharField(blank=True, max_length=10)),
                ('dream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreams.Dream')),
            ],
        ),
    ]
