# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-20 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0008_historial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idioma',
            name='p2_opcion1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='idioma',
            name='p2_opcion2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='idioma',
            name='p2_opcion3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='idioma',
            name='p2_opcion4',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
