# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-20 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0009_auto_20180420_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='idioma',
            name='add_agradable',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='idioma',
            name='add_desagradable',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
