# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-20 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0010_auto_20180420_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='idioma',
            name='label_p1',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='idioma',
            name='label_p2',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
