# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-20 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0011_auto_20180420_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='idioma',
            name='cerrar_sesion',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='idioma',
            name='crear_sueno',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='idioma',
            name='idioma',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='idioma',
            name='mi_sueno',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
