# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-20 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0012_auto_20180420_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='idioma',
            name='sub_sueno',
            field=models.CharField(blank=True, max_length=800),
        ),
    ]
