# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-22 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0013_idioma_sub_sueno'),
    ]

    operations = [
        migrations.AddField(
            model_name='idioma',
            name='instruccion_3',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='idioma',
            name='instruccion_4',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='idioma',
            name='instruccion_5',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='idioma',
            name='instruccion_6',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='idioma',
            name='instruccion_7',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='idioma',
            name='sub_buho1',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='idioma',
            name='sub_buho2',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='idioma',
            name='sub_buho3',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='idioma',
            name='sub_buho4',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='idioma',
            name='sub_buho5',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='idioma',
            name='sub_buho6',
            field=models.TextField(blank=True, max_length=800),
        ),
    ]
